# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "fc55ef90-5d5f-4bda-9e35-ad14767ae332"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build the release variant
  build_android_app(task: "assembleRelease")

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "5c799c7444bb17e9d9e5d3b1165884013197d6fa",
    build_secret: "731ecc0af2b8b39b551d8a54214f800326305d0fb115bf18d18d31214ea6d747"
  )
end
